name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          file_name: .env
          fail_on_empty: false
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_PORT: ${{ secrets.MAIL_PORT}}
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          MAIL_SSL: ${{ secrets.MAIL_SSL }}
          MAIL_TLS: ${{ secrets.MAIL_TLS }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}

      - name: Build Docker images
        run: |
          docker compose build --force-rm --no-cache

  run:
    runs-on: self-hosted

    needs:
      - build

    steps:
      - name: Run Docker images
        run: |
          docker compose up -d --remove-orphans
